-- ==========================================
-- 022_soal_bing_k3_duolingo.sql
-- Seed Duolingo-style questions for B.Inggris K3
-- ==========================================

DELETE FROM public.questions WHERE material_id LIKE 'k3-bing-%';

INSERT INTO public.questions (
  id, material_id, tipe, soal, soal_id, data, audio_text, pilihan, jawaban_benar, penjelasan_id, kalimat, kata, level, xp
) VALUES
(
  'k3-bing-01-q1',
  'k3-bing-01',
  'match',
  'Match the picture with the correct word!',
  'Pilih gambar yang sesuai dengan kata!',
  '{"🍗":["fried chicken","noodle","rice"],"🍜":["meatball","noodle","bread"],"🍚":["fried rice","rice","tea"]}'::jsonb,
  NULL,
  NULL,
  '{"🍗":"fried chicken","🍜":"noodle","🍚":"rice"}'::jsonb,
  '🍗 = fried chicken (ayam goreng), 🍜 = noodle (mi), 🍚 = rice (nasi). Great job! 🌟',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-01-q2',
  'k3-bing-01',
  'listen_choose',
  'Listen and choose the correct picture!',
  'Dengar dan pilih gambar yang benar!',
  NULL,
  'fried chicken',
  '["🍗","🍜","🍚"]'::jsonb,
  '"🍗"'::jsonb,
  'Fried chicken = ayam goreng = 🍗. Yummy! 🎉',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-01-q3',
  'k3-bing-01',
  'arrange',
  'Arrange the words into a correct sentence!',
  'Susun kata-kata menjadi kalimat yang benar!',
  NULL,
  NULL,
  NULL,
  '"I like fried chicken"'::jsonb,
  'I like fried chicken = Saya suka ayam goreng. Ingat: Subject (I) + like + object! ✅',
  NULL,
  '["like","I","chicken","fried"]'::jsonb,
  1,
  15
),
(
  'k3-bing-01-q4',
  'k3-bing-01',
  'fill_blank',
  'Fill in the blank!',
  'Lengkapi kalimatnya!',
  NULL,
  NULL,
  '["like","is","are"]'::jsonb,
  '"like"'::jsonb,
  'I LIKE fried rice = Saya suka nasi goreng. ''Like'' artinya suka! 🍛',
  'I ___ fried rice.',
  NULL,
  1,
  10
),
(
  'k3-bing-01-q5',
  'k3-bing-01',
  'choose_correct',
  'What is this? 🍦',
  'Apa ini? 🍦',
  NULL,
  NULL,
  '["ice cream","milk","tea"]'::jsonb,
  '"ice cream"'::jsonb,
  '🍦 = ice cream = es krim. Sweet! 🍦',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-01-q6',
  'k3-bing-01',
  'true_false',
  '''Meatball'' artinya bakso. True or False?',
  '''Meatball'' artinya bakso. Benar atau Salah?',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"True"'::jsonb,
  'Betul! Meatball = bakso = 🍡. Yummy! 🎉',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-01-q7',
  'k3-bing-01',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"I like milk"'::jsonb,
  'I like milk = Saya suka susu. 🥛',
  NULL,
  '["milk","like","I"]'::jsonb,
  1,
  15
),
(
  'k3-bing-01-q8',
  'k3-bing-01',
  'match',
  'Match the English word with Indonesian meaning!',
  'Cocokkan kata Inggris dengan arti Indonesia!',
  '{"coffee":["teh","kopi","susu"],"tea":["kopi","teh","es krim"],"bread":["nasi","roti","bakso"]}'::jsonb,
  NULL,
  NULL,
  '{"coffee":"kopi","tea":"teh","bread":"roti"}'::jsonb,
  'Coffee = kopi ☕, Tea = teh 🍵, Bread = roti 🍞. Perfect! ⭐',
  NULL,
  NULL,
  2,
  10
),
(
  'k3-bing-02-q1',
  'k3-bing-02',
  'choose_correct',
  '''I don''t like'' artinya...',
  '''I don''t like'' artinya...',
  NULL,
  NULL,
  '["Saya suka","Saya tidak suka","Saya mau"]'::jsonb,
  '"Saya tidak suka"'::jsonb,
  'Don''t = tidak. Jadi ''I don''t like'' = Saya tidak suka. 👎',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-02-q2',
  'k3-bing-02',
  'fill_blank',
  '___ you like noodles?',
  '___ kamu suka mi?',
  NULL,
  NULL,
  '["Do","Are","Is"]'::jsonb,
  '"Do"'::jsonb,
  '''Do you like...?'' = Apakah kamu suka...? Untuk tanya ''suka'', pakai ''Do''! 💡',
  '___ you like noodles?',
  NULL,
  1,
  10
),
(
  'k3-bing-02-q3',
  'k3-bing-02',
  'arrange',
  'Arrange into a question!',
  'Susun menjadi pertanyaan!',
  NULL,
  NULL,
  NULL,
  '"Do you like rice"'::jsonb,
  'Do you like rice? = Apakah kamu suka nasi? 🍚',
  NULL,
  '["like","you","Do","rice"]'::jsonb,
  1,
  15
),
(
  'k3-bing-02-q4',
  'k3-bing-02',
  'choose_correct',
  'Do you like coffee? (jawaban positif)',
  'Do you like coffee? (jawaban positif)',
  NULL,
  NULL,
  '["Yes, I do.","No, I don''t.","I like tea."]'::jsonb,
  '"Yes, I do."'::jsonb,
  '''Yes, I do.'' = Ya, saya suka. Untuk jawab positif dari ''Do you like...?'' ✅',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-02-q5',
  'k3-bing-02',
  'true_false',
  '''No, I don''t like it.'' artinya ''Ya, saya suka.''',
  '''No, I don''t like it.'' artinya ''Ya, saya suka.''',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! ''No, I don''t like it.'' = Tidak, saya tidak suka. 👎',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-02-q6',
  'k3-bing-02',
  'fill_blank',
  'A: Do you like meatball? B: ___, I don''t.',
  'A: Do you like meatball? B: ___, saya tidak.',
  NULL,
  NULL,
  '["Yes","No","Maybe"]'::jsonb,
  '"No"'::jsonb,
  '''No, I don''t.'' = Tidak, saya tidak (suka). 👎',
  'A: Do you like meatball? B: ___, I don''t.',
  NULL,
  1,
  10
),
(
  'k3-bing-02-q7',
  'k3-bing-02',
  'match',
  'Match the expression with the meaning!',
  'Cocokkan ungkapan dengan artinya!',
  '{"I like it.":["Saya tidak suka","Saya suka","Saya mau"],"I don''t like it.":["Saya suka","Saya tidak suka","Saya punya"],"Do you like it?":["Apakah kamu punya?","Apakah kamu suka?","Apakah kamu mau?"]}'::jsonb,
  NULL,
  NULL,
  '{"I like it.":"Saya suka","I don''t like it.":"Saya tidak suka","Do you like it?":"Apakah kamu suka?"}'::jsonb,
  'I like it = Saya suka 👍, I don''t like it = Saya tidak suka 👎, Do you like it? = Apakah kamu suka? ❓',
  NULL,
  NULL,
  2,
  10
),
(
  'k3-bing-02-q8',
  'k3-bing-02',
  'arrange',
  'Arrange into a correct answer!',
  'Susun menjadi jawaban yang benar!',
  NULL,
  NULL,
  NULL,
  '"Yes I do"'::jsonb,
  'Yes, I do. = Ya, saya suka. Jangan lupa koma setelah Yes! ✅',
  NULL,
  '["do","Yes","I"]'::jsonb,
  2,
  15
),
(
  'k3-bing-03-q1',
  'k3-bing-03',
  'choose_correct',
  '''Breakfast'' artinya...',
  '''Breakfast'' artinya...',
  NULL,
  NULL,
  '["Sarapan","Makan siang","Makan malam"]'::jsonb,
  '"Sarapan"'::jsonb,
  'Breakfast = sarapan 🌅, Lunch = makan siang 🌞, Dinner = makan malam 🌙',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-03-q2',
  'k3-bing-03',
  'match',
  'Match the meal with the time!',
  'Cocokkan makanan dengan waktunya!',
  '{"breakfast":["12:00","07:00","19:00"],"lunch":["07:00","12:00","19:00"],"dinner":["19:00","07:00","12:00"]}'::jsonb,
  NULL,
  NULL,
  '{"breakfast":"07:00","lunch":"12:00","dinner":"19:00"}'::jsonb,
  'Breakfast = 07:00 pagi 🌅, Lunch = 12:00 siang 🌞, Dinner = 19:00 malam 🌙',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-03-q3',
  'k3-bing-03',
  'fill_blank',
  'I ___ bread and milk for breakfast.',
  'Saya ___ roti dan susu untuk sarapan.',
  NULL,
  NULL,
  '["have","like","eat"]'::jsonb,
  '"have"'::jsonb,
  '''I have... for breakfast'' = Saya makan/minum... untuk sarapan. 🍞🥛',
  'I ___ bread and milk for breakfast.',
  NULL,
  1,
  10
),
(
  'k3-bing-03-q4',
  'k3-bing-03',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"I have fried chicken for lunch"'::jsonb,
  'I have fried chicken for lunch = Saya makan ayam goreng untuk makan siang. 🍗',
  NULL,
  '["for","chicken","I","have","lunch","fried"]'::jsonb,
  1,
  15
),
(
  'k3-bing-03-q5',
  'k3-bing-03',
  'choose_correct',
  'What do you have for dinner? 🌙',
  'Apa yang kamu makan untuk makan malam? 🌙',
  NULL,
  NULL,
  '["Rice and meatball","Bread and milk","Fried chicken"]'::jsonb,
  '"Rice and meatball"'::jsonb,
  'Semua bisa benar! Tapi ''rice and meatball'' = nasi dan bakso adalah makanan malam yang umum di Indonesia. 🍚🍡',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-03-q6',
  'k3-bing-03',
  'true_false',
  '''Lunch'' artinya sarapan.',
  '''Lunch'' artinya sarapan.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! Lunch = makan siang, Breakfast = sarapan. 🌞 vs 🌅',
  NULL,
  NULL,
  1,
  10
),
(
  'k3-bing-03-q7',
  'k3-bing-03',
  'fill_blank',
  'I have noodles ___ dinner.',
  'Saya makan mi ___ makan malam.',
  NULL,
  NULL,
  '["for","in","on"]'::jsonb,
  '"for"'::jsonb,
  '''For'' digunakan untuk menyatakan makanan pada waktu tertentu. ''I have noodles for dinner.'' 🍜',
  'I have noodles ___ dinner.',
  NULL,
  2,
  10
),
(
  'k3-bing-03-q8',
  'k3-bing-03',
  'listen_choose',
  'Listen and choose!',
  'Dengar dan pilih!',
  NULL,
  'breakfast',
  '["🌅","🌞","🌙"]'::jsonb,
  '"🌅"'::jsonb,
  'Breakfast = sarapan = pagi = 🌅. Rise and shine! ☀️',
  NULL,
  NULL,
  1,
  10
),
(
  'q1',
  'k3-bing-04',
  'match',
  'Match the hobby with the emoji!',
  'Cocokkan hobi dengan emoji!',
  '{"🏊":["reading","swimming","singing"],"📚":["swimming","reading","dancing"],"🚴":["running","riding a bike","playing football"]}'::jsonb,
  NULL,
  NULL,
  '{"🏊":"swimming","📚":"reading","🚴":"riding a bike"}'::jsonb,
  '🏊 = swimming (berenang), 📚 = reading (membaca), 🚴 = riding a bike (bersepeda). Great! 🌟',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-04',
  'choose_correct',
  '''Swimming'' artinya...',
  '''Swimming'' artinya...',
  NULL,
  NULL,
  '["Berenang","Bernyanyi","Berlari"]'::jsonb,
  '"Berenang"'::jsonb,
  'Swimming = berenang 🏊, Singing = bernyanyi 🎤, Running = berlari 🏃',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-04',
  'fill_blank',
  'Do you like ___? (bermain bola)',
  'Do you like ___? (bermain bola)',
  NULL,
  NULL,
  '["playing football","swimming","reading"]'::jsonb,
  '"playing football"'::jsonb,
  'Playing football = bermain bola ⚽. Do you like playing football? 🥅',
  'Do you like ___?',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-04',
  'arrange',
  'Arrange into a question!',
  'Susun menjadi pertanyaan!',
  NULL,
  NULL,
  NULL,
  '"Do you like swimming"'::jsonb,
  'Do you like swimming? = Apakah kamu suka berenang? 🏊',
  NULL,
  '["like","you","swimming","Do"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-04',
  'choose_correct',
  'Does Made like reading? (jawaban negatif)',
  'Does Made like reading? (jawaban negatif)',
  NULL,
  NULL,
  '["Yes, he does.","No, he doesn''t.","Yes, I do."]'::jsonb,
  '"No, he doesn''t."'::jsonb,
  '''No, he doesn''''t.'' = Tidak, dia tidak (suka). Untuk laki-laki (he), pakai ''doesn''''t''. 👎',
  NULL,
  NULL,
  2,
  10
),
(
  'q6',
  'k3-bing-04',
  'true_false',
  '''Riding a bike'' artinya berlari.',
  '''Riding a bike'' artinya berlari.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! Riding a bike = bersepeda 🚴, Running = berlari 🏃',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-04',
  'fill_blank',
  'Cici likes ___. (menyanyi)',
  'Cici likes ___. (menyanyi)',
  NULL,
  NULL,
  '["singing","swimming","dancing"]'::jsonb,
  '"singing"'::jsonb,
  'Cici likes singing = Cici suka menyanyi. 🎤 ''Likes'' untuk dia (she/he).',
  'Cici likes ___.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-04',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"Made likes riding a bike"'::jsonb,
  'Made likes riding a bike = Made suka bersepeda. 🚴 Nama orang + likes + hobby.',
  NULL,
  '["a","likes","bike","Made","riding"]'::jsonb,
  2,
  15
),
(
  'q1',
  'k3-bing-05',
  'choose_correct',
  '''Sunday'' artinya...',
  '''Sunday'' artinya...',
  NULL,
  NULL,
  '["Minggu","Senin","Sabtu"]'::jsonb,
  '"Minggu"'::jsonb,
  'Sunday = Minggu ☀️, Monday = Senin, Saturday = Sabtu',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-05',
  'match',
  'Match the day with the correct order!',
  'Cocokkan hari dengan urutan yang benar!',
  '{"Monday":["Hari ke-2","Hari ke-1","Hari ke-7"],"Wednesday":["Hari ke-3","Hari ke-4","Hari ke-5"],"Friday":["Hari ke-5","Hari ke-6","Hari ke-4"]}'::jsonb,
  NULL,
  NULL,
  '{"Monday":"Hari ke-1","Wednesday":"Hari ke-3","Friday":"Hari ke-5"}'::jsonb,
  'Monday = hari ke-1 📅, Wednesday = hari ke-3, Friday = hari ke-5. In Indonesia, Monday is the first day of the week! 🇮🇩',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-05',
  'fill_blank',
  'I like swimming on ___.',
  'Saya suka berenang pada hari ___.',
  NULL,
  NULL,
  '["Saturday","Sunday","Monday"]'::jsonb,
  '"Saturday"'::jsonb,
  'I like swimming on Saturday = Saya suka berenang hari Sabtu. 🏊 Bisa juga hari lain!',
  'I like swimming on ___.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-05',
  'arrange',
  'Arrange the days in order!',
  'Susun hari sesuai urutan!',
  NULL,
  NULL,
  NULL,
  '"Monday Tuesday Wednesday"'::jsonb,
  'Monday → Tuesday → Wednesday = Senin → Selasa → Rabu. 📅',
  NULL,
  '["Wednesday","Monday","Tuesday"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-05',
  'choose_correct',
  'What day is today? (jika hari ini Senin)',
  'Hari ini hari apa? (jika hari ini Senin)',
  NULL,
  NULL,
  '["Today is Monday.","Today is Sunday.","Today is Friday."]'::jsonb,
  '"Today is Monday."'::jsonb,
  'Today is Monday = Hari ini Senin. ''Today'' = hari ini. 📅',
  NULL,
  NULL,
  1,
  10
),
(
  'q6',
  'k3-bing-05',
  'true_false',
  '''Friday'' artinya Kamis.',
  '''Friday'' artinya Kamis.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! Friday = Jumat 🕌, Thursday = Kamis',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-05',
  'fill_blank',
  'I like reading on ___. (hari Sabtu dan Minggu)',
  'Saya suka membaca pada hari ___. (Sabtu dan Minggu)',
  NULL,
  NULL,
  '["weekend","weekday","holiday"]'::jsonb,
  '"weekend"'::jsonb,
  'Weekend = akhir pekan (Sabtu & Minggu). Weekday = hari kerja (Senin–Jumat). 📅',
  'I like reading on ___.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-05',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"I like riding a bike on Sunday"'::jsonb,
  'I like riding a bike on Sunday = Saya suka bersepeda hari Minggu. 🚴☀️',
  NULL,
  '["Sunday","on","like","I","riding","a","bike"]'::jsonb,
  2,
  15
),
(
  'q1',
  'k3-bing-06',
  'match',
  'Match the place with the emoji!',
  'Cocokkan tempat dengan emoji!',
  '{"🍽️":["library","canteen","classroom"],"📚":["canteen","library","office"],"🖥️":["schoolyard","computer lab","restroom"]}'::jsonb,
  NULL,
  NULL,
  '{"🍽️":"canteen","📚":"library","🖥️":"computer lab"}'::jsonb,
  '🍽️ = canteen (kantin), 📚 = library (perpustakaan), 🖥️ = computer lab (lab komputer). 🏫',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-06',
  'choose_correct',
  '''Library'' artinya...',
  '''Library'' artinya...',
  NULL,
  NULL,
  '["Perpustakaan","Kantin","Kelas"]'::jsonb,
  '"Perpustakaan"'::jsonb,
  'Library = perpustakaan 📚, Canteen = kantin 🍽️, Classroom = kelas 🏫',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-06',
  'fill_blank',
  'Is it the classroom? ___, it is.',
  'Apakah ini kelas? ___, ini kelas.',
  NULL,
  NULL,
  '["Yes","No","Maybe"]'::jsonb,
  '"Yes"'::jsonb,
  '''Yes, it is.'' = Ya, ini (kelas). Untuk jawab positif dari ''Is it...?'' ✅',
  'Is it the classroom? ___, it is.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-06',
  'arrange',
  'Arrange into a question!',
  'Susun menjadi pertanyaan!',
  NULL,
  NULL,
  NULL,
  '"Is it the canteen"'::jsonb,
  'Is it the canteen? = Apakah ini kantin? 🍽️',
  NULL,
  '["canteen","it","Is","the"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-06',
  'choose_correct',
  'Is it the library? (jawaban negatif)',
  'Apakah ini perpustakaan? (jawaban negatif)',
  NULL,
  NULL,
  '["Yes, it is.","No, it isn''t.","No, I don''t."]'::jsonb,
  '"No, it isn''t."'::jsonb,
  '''No, it isn''''t.'' = Tidak, ini bukan. ''Isn''''t'' = is + not. 👎',
  NULL,
  NULL,
  2,
  10
),
(
  'q6',
  'k3-bing-06',
  'true_false',
  '''Prayer room'' artinya mushola.',
  '''Prayer room'' artinya mushola.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"True"'::jsonb,
  'Betul! Prayer room = mushola 🕌. Restroom = toilet 🚻',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-06',
  'fill_blank',
  '___ it the office? No, it isn''t.',
  '___ ini kantor? Tidak, ini bukan.',
  NULL,
  NULL,
  '["Is","Are","Do"]'::jsonb,
  '"Is"'::jsonb,
  '''Is it...?'' untuk bertanya tentang tempat/benda. ''Is'' untuk satu (it). ❓',
  '___ it the office? No, it isn''t.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-06',
  'listen_choose',
  'Listen and choose!',
  'Dengar dan pilih!',
  NULL,
  'classroom',
  '["🏫","🍽️","📚"]'::jsonb,
  '"🏫"'::jsonb,
  'Classroom = kelas = 🏫. This is where we study! 📖',
  NULL,
  NULL,
  1,
  10
),
(
  'q1',
  'k3-bing-07',
  'choose_correct',
  '''Behind'' artinya...',
  '''Behind'' artinya...',
  NULL,
  NULL,
  '["Di belakang","Di depan","Di samping"]'::jsonb,
  '"Di belakang"'::jsonb,
  'Behind = di belakang, In front of = di depan, Beside = di samping',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-07',
  'match',
  'Match the preposition with the position!',
  'Cocokkan preposisi dengan posisi!',
  '{"in":["Di luar","Di dalam","Di atas"],"on":["Di bawah","Di atas","Di samping"],"under":["Di atas","Di bawah","Di antara"]}'::jsonb,
  NULL,
  NULL,
  '{"in":"Di dalam","on":"Di atas","under":"Di bawah"}'::jsonb,
  'In = di dalam 📦, On = di atas ⬆️, Under = di bawah ⬇️',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-07',
  'fill_blank',
  'The book is ___ the table.',
  'Bukunya ada ___ meja.',
  NULL,
  NULL,
  '["on","in","under"]'::jsonb,
  '"on"'::jsonb,
  'The book is ON the table = Bukunya di atas meja. 📚⬆️',
  'The book is ___ the table.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-07',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"The class is behind the office"'::jsonb,
  'The class is behind the office = Kelasnya di belakang kantor. 🏫',
  NULL,
  '["the","is","office","class","The","behind"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-07',
  'choose_correct',
  'Where is the canteen? (di samping perpustakaan)',
  'Di mana kantinnya? (di samping perpustakaan)',
  NULL,
  NULL,
  '["The canteen is beside the library.","The canteen is behind the library.","The canteen is under the library."]'::jsonb,
  '"The canteen is beside the library."'::jsonb,
  'Beside = di samping. The canteen is beside the library = Kantinnya di samping perpustakaan. 📚🍽️',
  NULL,
  NULL,
  2,
  10
),
(
  'q6',
  'k3-bing-07',
  'true_false',
  '''Between'' artinya di depan.',
  '''Between'' artinya di depan.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! Between = di antara, In front of = di depan. ↔️',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-07',
  'fill_blank',
  'The library is ___ the classroom and the office.',
  'Perpustakaannya ada ___ kelas dan kantor.',
  NULL,
  NULL,
  '["between","behind","in front of"]'::jsonb,
  '"between"'::jsonb,
  'Between = di antara dua benda. The library is between the classroom and the office. ↔️',
  'The library is ___ the classroom and the office.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-07',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"The chair is under the table"'::jsonb,
  'The chair is under the table = Kursinya di bawah meja. ⬇️',
  NULL,
  '["under","The","is","the","chair","table"]'::jsonb,
  2,
  15
),
(
  'q1',
  'k3-bing-08',
  'match',
  'Match the activity with the place!',
  'Cocokkan aktivitas dengan tempat!',
  '{"study":["Canteen","Classroom","Schoolyard"],"eat":["Classroom","Canteen","Library"],"play":["Library","Schoolyard","Classroom"]}'::jsonb,
  NULL,
  NULL,
  '{"study":"Classroom","eat":"Canteen","play":"Schoolyard"}'::jsonb,
  'Study in classroom 📖, Eat in canteen 🍽️, Play in schoolyard ⚽',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-08',
  'choose_correct',
  '''Teach'' artinya...',
  '''Teach'' artinya...',
  NULL,
  NULL,
  '["Mengajar","Belajar","Membaca"]'::jsonb,
  '"Mengajar"'::jsonb,
  'Teach = mengajar 👨‍🏫, Study = belajar 📖, Read = membaca 📚',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-08',
  'fill_blank',
  'I ___ orange juice in the canteen.',
  'Saya ___ jus jeruk di kantin.',
  NULL,
  NULL,
  '["drink","eat","play"]'::jsonb,
  '"drink"'::jsonb,
  'Drink = minum 🥤, Eat = makan 🍽️, Play = bermain ⚽. I drink orange juice = Saya minum jus jeruk.',
  'I ___ orange juice in the canteen.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-08',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"We pray in the prayer room"'::jsonb,
  'We pray in the prayer room = Kita berdoa di mushola. 🕌',
  NULL,
  '["the","pray","We","in","room","prayer"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-08',
  'choose_correct',
  'What do you do in the classroom?',
  'Apa yang kamu lakukan di kelas?',
  NULL,
  NULL,
  '["I study and read.","I eat and drink.","I play football."]'::jsonb,
  '"I study and read."'::jsonb,
  'In the classroom, we study and read! 📖 Di canteen, we eat and drink. 🍽️',
  NULL,
  NULL,
  1,
  10
),
(
  'q6',
  'k3-bing-08',
  'true_false',
  '''Write'' artinya membaca.',
  '''Write'' artinya membaca.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"False"'::jsonb,
  'Salah! Write = menulis ✍️, Read = membaca 📖',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-08',
  'fill_blank',
  'The teacher ___ in the classroom.',
  'Guru ___ di kelas.',
  NULL,
  NULL,
  '["teaches","studies","plays"]'::jsonb,
  '"teaches"'::jsonb,
  'The teacher teaches in the classroom = Guru mengajar di kelas. 👨‍🏫 ''Teaches'' untuk dia (he/she).',
  'The teacher ___ in the classroom.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-08',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"We play in the schoolyard"'::jsonb,
  'We play in the schoolyard = Kita bermain di halaman sekolah. ⚽',
  NULL,
  '["in","play","the","We","schoolyard"]'::jsonb,
  2,
  15
),
(
  'q1',
  'k3-bing-09',
  'match',
  'Match the adjective with the opposite!',
  'Cocokkan kata sifat dengan lawannya!',
  '{"clean":["dirty","small","narrow"],"big":["small","dirty","wide"],"wide":["narrow","clean","big"]}'::jsonb,
  NULL,
  NULL,
  '{"clean":"dirty","big":"small","wide":"narrow"}'::jsonb,
  'Clean ↔ Dirty (bersih ↔ kotor), Big ↔ Small (besar ↔ kecil), Wide ↔ Narrow (lebar ↔ sempit). ⚖️',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-09',
  'choose_correct',
  '''Clean'' artinya...',
  '''Clean'' artinya...',
  NULL,
  NULL,
  '["Bersih","Kotor","Besar"]'::jsonb,
  '"Bersih"'::jsonb,
  'Clean = bersih ✨, Dirty = kotor 🗑️, Big = besar 📏',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-09',
  'fill_blank',
  'My classroom is ___.',
  'Kelasku ___ .',
  NULL,
  NULL,
  '["big","small","dirty"]'::jsonb,
  '"big"'::jsonb,
  'My classroom is big = Kelasku besar. 🏫 ''Big'' = besar, ''Large'' juga = besar.',
  'My classroom is ___.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-09',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"My classroom is clean"'::jsonb,
  'My classroom is clean = Kelasku bersih. ✨ Subject + is + adjective.',
  NULL,
  '["is","classroom","My","clean"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-09',
  'choose_correct',
  'The schoolyard is ___. (luas)',
  'Halaman sekolahnya ___ . (luas)',
  NULL,
  NULL,
  '["wide","narrow","dirty"]'::jsonb,
  '"wide"'::jsonb,
  'Wide = lebar/luas ↔ Narrow = sempit. The schoolyard is wide = Halaman sekolahnya luas. 🏫',
  NULL,
  NULL,
  1,
  10
),
(
  'q6',
  'k3-bing-09',
  'true_false',
  '''Beautiful'' artinya indah.',
  '''Beautiful'' artinya indah.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"True"'::jsonb,
  'Betul! Beautiful = indah ✨. My school is beautiful = Sekolahku indah. 🌸',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-09',
  'fill_blank',
  'The restroom is ___. (kotor)',
  'Toiletnya ___ . (kotor)',
  NULL,
  NULL,
  '["dirty","clean","beautiful"]'::jsonb,
  '"dirty"'::jsonb,
  'Dirty = kotor. But we should keep it clean! 🧹 Let''s make it clean! ✨',
  'The restroom is ___.',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-09',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"My school is beautiful"'::jsonb,
  'My school is beautiful = Sekolahku indah. 🌸✨',
  NULL,
  '["is","school","My","beautiful"]'::jsonb,
  2,
  15
),
(
  'q1',
  'k3-bing-10',
  'match',
  'Match the number with the word!',
  'Cocokkan angka dengan kata!',
  '{"25":["twenty-five","thirty-five","forty-five"],"33":["thirty-three","twenty-three","forty-three"],"47":["forty-seven","thirty-seven","fifty-seven"]}'::jsonb,
  NULL,
  NULL,
  '{"25":"twenty-five","33":"thirty-three","47":"forty-seven"}'::jsonb,
  '25 = twenty-five, 33 = thirty-three, 47 = forty-seven. 🔢',
  NULL,
  NULL,
  1,
  10
),
(
  'q2',
  'k3-bing-10',
  'choose_correct',
  '''Thirty'' artinya...',
  '''Thirty'' artinya...',
  NULL,
  NULL,
  '["30","40","50"]'::jsonb,
  '"30"'::jsonb,
  'Thirty = 30, Forty = 40, Fifty = 50. 🔢',
  NULL,
  NULL,
  1,
  10
),
(
  'q3',
  'k3-bing-10',
  'fill_blank',
  'There ___ 20 books on the shelf.',
  'Ada ___ 20 buku di rak.',
  NULL,
  NULL,
  '["are","is","am"]'::jsonb,
  '"are"'::jsonb,
  '''There ARE'' untuk banyak (books = jamak). ''There IS'' untuk satu. 📚📚📚',
  'There ___ 20 books on the shelf.',
  NULL,
  1,
  10
),
(
  'q4',
  'k3-bing-10',
  'arrange',
  'Arrange into a sentence!',
  'Susun menjadi kalimat!',
  NULL,
  NULL,
  NULL,
  '"There are thirty chairs in the classroom"'::jsonb,
  'There are thirty chairs in the classroom = Ada 30 kursi di kelas. 🪑',
  NULL,
  '["are","There","chairs","thirty","the","in","classroom"]'::jsonb,
  1,
  15
),
(
  'q5',
  'k3-bing-10',
  'choose_correct',
  'There is ___ pencil on the table.',
  'Ada ___ pensil di meja.',
  NULL,
  NULL,
  '["a","two","three"]'::jsonb,
  '"a"'::jsonb,
  '''There IS a pencil'' = Ada satu pensil. ''A'' untuk satu. ✏️ ''There ARE'' untuk banyak.',
  NULL,
  NULL,
  2,
  10
),
(
  'q6',
  'k3-bing-10',
  'true_false',
  '''Forty-two'' artinya 42.',
  '''Forty-two'' artinya 42.',
  NULL,
  NULL,
  '["True","False"]'::jsonb,
  '"True"'::jsonb,
  'Betul! Forty-two = 42. Forty = 40, two = 2. 40 + 2 = 42! 🔢',
  NULL,
  NULL,
  1,
  10
),
(
  'q7',
  'k3-bing-10',
  'fill_blank',
  '___ there 25 students in the class?',
  '___ ada 25 siswa di kelas?',
  NULL,
  NULL,
  '["Are","Is","Do"]'::jsonb,
  '"Are"'::jsonb,
  '''Are there...?'' untuk bertanya tentang banyak benda/orang. ''Are'' untuk jamak (students). ❓',
  '___ there 25 students in the class?',
  NULL,
  2,
  10
),
(
  'q8',
  'k3-bing-10',
  'listen_choose',
  'Listen and choose!',
  'Dengar dan pilih!',
  NULL,
  'thirty-five',
  '["35","45","25"]'::jsonb,
  '"35"'::jsonb,
  'Thirty-five = 35. Thirty = 30, five = 5. 30 + 5 = 35! 🔢',
  NULL,
  NULL,
  1,
  10
);
